unstable_features = true

struct_field_align_threshold = 10
enum_discrim_align_threshold = 20

brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"

group_imports = "StdExternalCrate"
imports_granularity = "Module"

binop_separator = "Back"
blank_lines_upper_bound = 3
use_field_init_shorthand = true
reorder_impl_items = true
newline_style = "Unix"
match_block_trailing_comma = true
force_multiline_blocks = true
condense_wildcard_suffixes = true

max_width = 120